### ISSUE TITLE
Components should pass through classname

### ISSUE THREAD

**Issue by Weetbix** [VivyTeam/vivy-components#195]
Currently not all of our components pass through `className`, which makes them harder for users to style with `styled-components`. 

For example, `Row` and `Col`. We should consider adding this to all components.

**Comment by paschalidi** [comment]
yeah lets make it a standard for every new component we create. 
`style` and `className` should be there so you can actually change stuff. 
@Weetbix what do you think??

**Comment by paschalidi** [comment]
I think we decided not to go this path here. 
I will go ahead and close this. TO clean things up a bit
